apiVersion: apps/v1
kind: Deployment
metadata:
  name: survey-app-deployment
  labels:
    app: survey-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: survey-app
  template:
    metadata:
      labels:
        app: survey-app
    spec:
      containers:
        - name: survey-app
          image: vaishnavvarma/survey-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://survey-db.csngcimmuxcv.us-east-1.rds.amazonaws.com:3306/surveydb
            - name: SPRING_DATASOURCE_USERNAME
              value: admin
            - name: SPRING_DATASOURCE_PASSWORD
              value: Client6699